name: Build Furik Plugin

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: wp-cli
          
      - name: Install gettext
        run: sudo apt-get install -y gettext
        
      - name: Prepare build directory
        run: |
          mkdir -p build/furik
          cp -r includes admin payments shortcodes assets templates lang *.php *.md LICENSE build/furik/
          
      - name: Generate .mo files
        run: |
          cd build/furik
          msgfmt -o lang/furik-hu_HU.mo lang/furik-hu_HU.po
        
      - name: Create plugin zip
        run: |
          cd build
          zip -r furik.zip furik
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: furik-plugin
          path: build/furik.zip
          
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: build/furik.zip
          name: Furik Plugin ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
